services:
  sso:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env.docker
    environment:
      - APPLICATION_PORT=3000
    ports:
      - "${SSO_PORT:-3001}:3000"
    depends_on:
      - database

  sso-db:
    image: postgres:16.3
    restart: always
    env_file:
      - .env.docker
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
